name: mlcoursegpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.6.4
  - pip
  - numpy>=1.15.0
  - scipy>=1.4.0
  - cudatoolkit=11.0
  - scikit-learn 
  - scikit-image
  - pandas
  - matplotlib
  - seaborn
  - pylops
  - ipython
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - lightgbm
  - tqdm
  - pip:
    - cupy-cuda110
    - scooby
    - lasio
    - segyio
    - wandb
    - torchsummary
    - torchviz
    - lightgbm
    - xgboost
